/* GENERATED by scripts/build-images.mjs — do not edit by hand. */

export interface ImageAsset {
  src: string;
  srcSet: string;
  width: number;
  height: number;
  /** Intrinsic aspect ratio, so layout boxes never shift on load. */
  ratio: number;
  /** Inline base64 blur-up placeholder. */
  lqip: string;
}

export const portrait: ImageAsset = {
  src: '/img/portrait-560.webp',
  srcSet: "/img/portrait-200.webp 200w, /img/portrait-340.webp 340w, /img/portrait-560.webp 560w",
  width: 434,
  height: 574,
  ratio: 0.7561,
  lqip: 'data:image/webp;base64,UklGRpoBAABXRUJQVlA4WAoAAAAQAAAAFwAAHwAAQUxQSJUAAAART6CgbSM3diD2vvuPiICx/KNbCLexbavKlwa0gA804BA7uZN77hTwrQLeqfcKnkf0X4HbNoqPGZ5hvRW8UtmWattFU8R4k+f7kOtmQNHmxcQAGHNrAFg5mgPjHRmXOZF7xPZKXuWtjdJtdR/au6opgLb4B9KxtcahYitTikUzsLx+ClC8Dr3+xYCHvKck4Kwl5PijAABWUDgg3gAAANAFAJ0BKhgAIAA/BWqtT6ulpCI39VgBcCCJaAC34IAVxEbx7sDxy7Hw0sIf6oLs8ltPzGoNckAA/uLzQ1y+FsqcrP5lnmPzxQKsiZB0tUz5GpwOViQlm47IxxtJk9svQuvOBAGq0OySBjPf9Qi/uSUwiFT3dqtNkDgNZBgT/TbcFXd2OotgG5Is6bms7JNrtzQYGuPSjyu7Sm5myqughLiIsQlF9Wf7osiK11S7jFZKk/MXX6xRB13uaRGoj/S4kN2LanwKiPr52jOHdx3Sef+cMRnvzfT+LSZbCe0AAA==',
};

export const projectImage_titan: ImageAsset = {
  src: '/img/projects/titan-1200.webp',
  srcSet: "/img/projects/titan-480.webp 480w, /img/projects/titan-800.webp 800w, /img/projects/titan-1200.webp 1200w",
  width: 1348,
  height: 652,
  ratio: 2.0675,
  lqip: 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAwCdASoYAAwAPwl4s1Erp6SisAgBcCEJYwCdAB6ScyebqmzggADylaGgMFUhSb3TgOJej9fhinO4C0VAurQbIe8Cw88EvLERDIcvIdqm/XrGgAA=',
};

export const projectImage_luxora: ImageAsset = {
  src: '/img/projects/luxora-1200.webp',
  srcSet: "/img/projects/luxora-480.webp 480w, /img/projects/luxora-800.webp 800w, /img/projects/luxora-1200.webp 1200w",
  width: 1348,
  height: 652,
  ratio: 2.0675,
  lqip: 'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoYAAwAPwlusE+rpiSiMAgBcCEJQBOgBDv4P/Uh7cfoioAA/up8FOmZNRdxu0vq9zPgKyZPk77FcnE/T71Z8a9aiszFVphuZpbAAAAA',
};

export const projectImage_sallygreen: ImageAsset = {
  src: '/img/projects/sallygreen-1200.webp',
  srcSet: "/img/projects/sallygreen-480.webp 480w, /img/projects/sallygreen-800.webp 800w, /img/projects/sallygreen-1200.webp 1200w",
  width: 1348,
  height: 652,
  ratio: 2.0675,
  lqip: 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAABwAwCdASoYAAwAPwlwr1ArpiQisAgBcCEJaQAAW+fUyFpQQAAA/u6GkThZRJXdDvNjZs1eo4AAAA==',
};

export const projectImage_tastetrail: ImageAsset = {
  src: '/img/projects/tastetrail-1200.webp',
  srcSet: "/img/projects/tastetrail-480.webp 480w, /img/projects/tastetrail-800.webp 800w, /img/projects/tastetrail-1200.webp 1200w",
  width: 1348,
  height: 652,
  ratio: 2.0675,
  lqip: 'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoYAAwAPwlws0+rpqUiMAgBcCEJYgC7AGlYGkHtzSWEMAD++xPhIRZ6NOQzRX6nsN3aVsjuvuhgjl/kFQ7ZPjLpGUdFBClKmYyceFVTyhBkPGQA',
};

export const projectImage_jbet: ImageAsset = {
  src: '/img/projects/jbet-1200.webp',
  srcSet: "/img/projects/jbet-480.webp 480w, /img/projects/jbet-800.webp 800w, /img/projects/jbet-1200.webp 1200w",
  width: 1348,
  height: 652,
  ratio: 2.0675,
  lqip: 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAwCdASoYAAwAPwl0s1CrpySisAgBcCEJYwAAW+HrQZPLip/AAP6LVv9g4Ze/g8Ze6VRc8x63hA2mNUZuAAAA',
};
