/* GENERATED by scripts/build-images.mjs — do not edit by hand. */

export interface ImageAsset {
  src: string;
  srcSet: string;
  width: number;
  height: number;
  /** Intrinsic aspect ratio, so layout boxes never shift on load. */
  ratio: number;
  /** Inline base64 blur-up placeholder. */
  lqip: string;
}

export const portrait: ImageAsset = {
  src: '/img/portrait-340.webp',
  srcSet: "/img/portrait-200.webp 200w, /img/portrait-340.webp 340w",
  width: 326,
  height: 765,
  ratio: 0.4261,
  lqip: 'data:image/webp;base64,UklGRvQCAABXRUJQVlA4WAoAAAAQAAAAFwAANwAAQUxQSDMBAAART6CgbRsWl8bfIiLA/M2qAbe29rbNR2oBmKFXgmor0bUie+U6yzWp1EcsYOGf9//B4xEi+j8BAKAG58siBFf98/t9HfusebJEdA0BqIklIjKJB1QeJB5DYPKRTASVk0Or1tNBjcrWOkyjeXq7dGWwsy58tT6OGCg/pVsElB+CSX1A5Zbd6h6A/skSUeoDgOo/iUziMZRzS2YRCs2TJXPVwsQSEaUe2xBf+QBULvyGAMoP4RaxP8FoAM2PQAmAniNlVjAJgOZL0gDKDykCoPJ/uAlZEThCtpFKbGLZ0Wc9YSU0Pyz1WPnBfgR1FyDkLHFdX0WWT1dGaV4kyakhIKMkM1raGL1xrY1evx2Tdzx5R45r1CsS9l4FSsWaL+04FlCbo//9TDwhT71yPvZZeas91R/5AFZQOCCaAQAAMAkAnQEqGAA4AD8JdrBRK6ekoqgNUXAhCWgAv2vneHQsyqm1MGzTgkXmzN4ReEZRbkdGfmOWiVORWFPkN4Sf3Fo94Rlt2edpTed6w6uxiGncAAD9FLRUwHzlL8/1EF1PI1HLUVGFUvE4U9z1HGH3SEaCGXfnLEzdcmU6p+4RqBUEEudvz+o/X4yCK/E5TWhRK5GcybW3ic4uTmi8lhqcdRBJ+45NeMix2YVU7pztYOSmq/EDA8XrEj9qBuuFv+F+hmyw3Hg+KNFG2xwzQl0STtFcWnq2RGFDJKSZ+1pjGDqhWbsc4lyizDX0pm9OgmcrVmzPnPBVgkYDMP6I90/gH+pKYtWol7A1vbscK7RmDnw4Z4SXWX1uu2VKeM5HNowLs5p5pWhpRSdSzY6Am9dOQB1J8x7MIdt3jXybJkpGWzB4Ff2BibBEZiDApG6TLRR780nGvTq1CrNQSc1zlJcbgeP5CXXR9+zrv1M6Hs6r/gQS6DI1sLATUikrio8KUpoYtKZXxEzTPDFhKg4XN6VegBZ+H+g/gIuAAAA=',
};

export const projectImage_titan: ImageAsset = {
  src: '/img/projects/titan-1200.webp',
  srcSet: "/img/projects/titan-480.webp 480w, /img/projects/titan-800.webp 800w, /img/projects/titan-1200.webp 1200w",
  width: 1348,
  height: 652,
  ratio: 2.0675,
  lqip: 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAwCdASoYAAwAPwl4s1Erp6SisAgBcCEJYwCdAB6ScyebqmzggADylaGgMFUhSb3TgOJej9fhinO4C0VAurQbIe8Cw88EvLERDIcvIdqm/XrGgAA=',
};

export const projectImage_luxora: ImageAsset = {
  src: '/img/projects/luxora-1200.webp',
  srcSet: "/img/projects/luxora-480.webp 480w, /img/projects/luxora-800.webp 800w, /img/projects/luxora-1200.webp 1200w",
  width: 1348,
  height: 652,
  ratio: 2.0675,
  lqip: 'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoYAAwAPwlusE+rpiSiMAgBcCEJQBOgBDv4P/Uh7cfoioAA/up8FOmZNRdxu0vq9zPgKyZPk77FcnE/T71Z8a9aiszFVphuZpbAAAAA',
};

export const projectImage_sallygreen: ImageAsset = {
  src: '/img/projects/sallygreen-1200.webp',
  srcSet: "/img/projects/sallygreen-480.webp 480w, /img/projects/sallygreen-800.webp 800w, /img/projects/sallygreen-1200.webp 1200w",
  width: 1348,
  height: 652,
  ratio: 2.0675,
  lqip: 'data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAABwAwCdASoYAAwAPwlwr1ArpiQisAgBcCEJaQAAW+fUyFpQQAAA/u6GkThZRJXdDvNjZs1eo4AAAA==',
};

export const projectImage_tastetrail: ImageAsset = {
  src: '/img/projects/tastetrail-1200.webp',
  srcSet: "/img/projects/tastetrail-480.webp 480w, /img/projects/tastetrail-800.webp 800w, /img/projects/tastetrail-1200.webp 1200w",
  width: 1348,
  height: 652,
  ratio: 2.0675,
  lqip: 'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoYAAwAPwlws0+rpqUiMAgBcCEJYgC7AGlYGkHtzSWEMAD++xPhIRZ6NOQzRX6nsN3aVsjuvuhgjl/kFQ7ZPjLpGUdFBClKmYyceFVTyhBkPGQA',
};

export const projectImage_jbet: ImageAsset = {
  src: '/img/projects/jbet-1200.webp',
  srcSet: "/img/projects/jbet-480.webp 480w, /img/projects/jbet-800.webp 800w, /img/projects/jbet-1200.webp 1200w",
  width: 1348,
  height: 652,
  ratio: 2.0675,
  lqip: 'data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAwCdASoYAAwAPwl0s1CrpySisAgBcCEJYwAAW+HrQZPLip/AAP6LVv9g4Ze/g8Ze6VRc8x63hA2mNUZuAAAA',
};
