/**
 * Image pipeline.
 *
 * The source assets were hand-placed and badly out of shape for the web:
 *   - hero.png / about.png were byte-identical duplicates, 248 KB each, for a
 *     434x574 image, and the portrait was loaded twice on the hero alone.
 *   - project screenshots are 1360x653 (about 2.08:1) but were being shown in a
 *     4:3 box with object-fit: cover, which sliced the page content in half.
 *
 * This script produces responsive WebP derivatives, a real intrinsic aspect
 * ratio per asset, and a tiny base64 LQIP used for a blur-up placeholder so the
 * layout never jumps and something meaningful paints immediately.
 *
 *   node scripts/build-images.mjs
 */
import { readFile, writeFile, mkdir, unlink } from 'node:fs/promises';
import { existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
/** Originals live outside public/ so the script is safely re-runnable. */
const SRC = path.join(ROOT, 'assets');
const IMG = path.join(ROOT, 'public', 'img');

/** Project screenshots: wide captures of the real apps. */
const PROJECTS = ['titan', 'luxora', 'sallygreen', 'tastetrail', 'jbet'];
const PROJECT_WIDTHS = [480, 800, 1200, 1600];

/** Portrait — deduped to a single source. */
const PORTRAIT_WIDTHS = [200, 340, 560];
const PORTRAIT_SOURCE = 'portrait.png';

const kb = (n) => `${(n / 1024).toFixed(1)} KB`;

const emit = async (name, buffer) => {
  const file = path.join(IMG, name);
  await writeFile(file, buffer);
  return { name, size: buffer.length };
};

/** Inline base64 LQIP, kept small enough to sit in the JS bundle cheaply. */
const lqip = async (input) => {
  const buf = await sharp(input)
    .resize(24, null, { fit: 'inside' })
    .blur(1.1)
    .webp({ quality: 32, alphaQuality: 40 })
    .toBuffer();
  return buf.toString('base64');
};

const buildProject = async (slug) => {
  const src = path.join(SRC, 'projects', `${slug}.webp`);
  const input = await readFile(src);
  const meta = await sharp(input).metadata();

  const outputs = [];
  for (const width of PROJECT_WIDTHS) {
    if (width > meta.width * 1.15) continue;
    const buf = await sharp(input)
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: width > 1000 ? 72 : 78, effort: 5 })
      .toBuffer();
    outputs.push(await emit(`projects/${slug}-${width}.webp`, buf));
  }

  return {
    slug,
    width: meta.width,
    height: meta.height,
    ratio: Number((meta.width / meta.height).toFixed(4)),
    widths: outputs.map((o) => Number(o.name.match(/-(\d+)\.webp$/)[1])),
    lqip: await lqip(input),
    bytes: outputs.reduce((a, o) => a + o.size, 0),
  };
};

const buildPortrait = async () => {
  const input = await readFile(path.join(SRC, PORTRAIT_SOURCE));
  const meta = await sharp(input).metadata();

  const outputs = [];
  for (const width of PORTRAIT_WIDTHS) {
    /* Same guard as the project images. Without it a small source silently
       produced files *named* 340 and 560 that were really 236px, and the
       generated srcset descriptors claimed widths the bytes did not have. */
    if (width > meta.width * 1.15) continue;
    const buf = await sharp(input)
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: 80, effort: 5 })
      .toBuffer();
    outputs.push(await emit(`portrait-${width}.webp`, buf));
  }

  return {
    width: meta.width,
    height: meta.height,
    ratio: Number((meta.width / meta.height).toFixed(4)),
    widths: outputs.map((o) => Number(o.name.match(/-(\d+)\.webp$/)[1])),
    lqip: await lqip(input),
    bytes: outputs.reduce((a, o) => a + o.size, 0),
  };
};

const main = async () => {
  await mkdir(path.join(IMG, 'projects'), { recursive: true });

  const projects = {};
  for (const slug of PROJECTS) projects[slug] = await buildProject(slug);
  const portrait = await buildPortrait();

  /* Retire any hand-placed originals that the derivatives replace. */
  for (const slug of PROJECTS) {
    const old = path.join(IMG, 'projects', `${slug}.webp`);
    if (existsSync(old)) await unlink(old);
  }
  for (const dead of ['hero.png', 'about.png']) {
    const old = path.join(IMG, dead);
    if (existsSync(old)) await unlink(old);
  }

  /* Drop portrait derivatives this run did not produce. A narrower source
     generates fewer sizes, and without this the previously generated ones
     linger in public/ and ship in the build while nothing references them. */
  for (const file of readdirSync(IMG)) {
    if (!file.startsWith('portrait-') || !file.endsWith('.webp')) continue;
    if (!portrait.widths.some((w) => file === `portrait-${w}.webp`)) {
      await unlink(path.join(IMG, file));
      console.log(`  retired ${file}`);
    }
  }

  await writeFile(
    path.join(ROOT, 'src', 'content', 'images.ts'),
    `/* GENERATED by scripts/build-images.mjs — do not edit by hand. */\n\n` +
      `export interface ImageAsset {\n` +
      `  src: string;\n  srcSet: string;\n  width: number;\n  height: number;\n` +
      `  /** Intrinsic aspect ratio, so layout boxes never shift on load. */\n` +
      `  ratio: number;\n  /** Inline base64 blur-up placeholder. */\n  lqip: string;\n}\n\n` +
      `export const portrait: ImageAsset = {\n` +
      `  src: '/img/portrait-${portrait.widths[portrait.widths.length - 1]}.webp',\n` +
      `  srcSet: ${JSON.stringify(portrait.widths.map((w) => `/img/portrait-${w}.webp ${w}w`).join(', '))},\n` +
      `  width: ${portrait.width},\n  height: ${portrait.height},\n` +
      `  ratio: ${portrait.ratio},\n  lqip: 'data:image/webp;base64,${portrait.lqip}',\n};\n\n` +
      Object.entries(projects)
        .map(
          ([slug, p]) =>
            `export const projectImage_${slug.replace(/-(\w)/g, (_, c) => c.toUpperCase())}: ImageAsset = {\n` +
            `  src: '/img/projects/${slug}-${p.widths[p.widths.length - 1]}.webp',\n` +
            `  srcSet: ${JSON.stringify(p.widths.map((w) => `/img/projects/${slug}-${w}.webp ${w}w`).join(', '))},\n` +
            `  width: ${p.width},\n  height: ${p.height},\n` +
            `  ratio: ${p.ratio},\n  lqip: 'data:image/webp;base64,${p.lqip}',\n};\n`
        )
        .join('\n')
  );

  /* ---- report ---- */
  const SOURCES = { titan: 31.6, luxora: 34.8, sallygreen: 31.0, tastetrail: 54.7, jbet: 35.6 };
  const before = 248.2 * 2 + Object.values(SOURCES).reduce((a, b) => a + b, 0);
  const after =
    Object.values(projects).reduce((a, p) => a + p.bytes, 0) + portrait.bytes;

  console.log('\nasset           was (1 size)   now (4 sizes)   worst-case request');
  console.log('-'.repeat(70));
  for (const [slug, p] of Object.entries(projects)) {
    const mid = p.widths[Math.min(2, p.widths.length - 1)];
    console.log(
      `${slug.padEnd(16)}${`${SOURCES[slug].toFixed(1)} KB`.padEnd(15)}` +
        `${`${kb(p.bytes)}`.padEnd(16)}${`${mid}w ≈ ${kb(p.bytes / 3)}`}`
    );
  }
  console.log(
    `${'portrait'.padEnd(16)}${'496.4 KB'.padEnd(15)}${`${kb(portrait.bytes)}`.padEnd(16)}340w ≈ ${kb(portrait.bytes * 0.4)}`
  );
  console.log('-'.repeat(70));
  console.log(
    `total on disk   ${kb(before * 1024)}`.padEnd(30) + `${kb(after)} across all sizes`
  );
  console.log(
    `\nWhat a visitor actually pulls is one size per image, not the sum —`
  );
  console.log(`the old build paid 248.2 KB twice for one 434px-wide portrait.`);
  console.log(`\nmanifest -> src/content/images.ts`);
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
